ALTER TABLE "users" ADD COLUMN "showEmail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "allowTagging" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN "publicProfile" BOOLEAN NOT NULL DEFAULT true;
